/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IHM;
import core.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
/**
 *
 * @author JD
 */
public class MainFrmApplication extends javax.swing.JFrame {

    static Connection connect;
    static Repertoire liste = new Repertoire();
    static CreateContact createFrame;
    static AfficheContact listeContact;
    /**
     * Creates new form MainFrmApplication
     */
    public MainFrmApplication() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        bandImage = new javax.swing.JLabel();
        welcomeText = new javax.swing.JLabel();
        newContactButton = new javax.swing.JButton();
        listContactButton = new javax.swing.JButton();
        storageButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Contact app - Accueil");
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 900, 2000));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                onWindowsClosed(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                onWindowsClosed(evt);
            }
        });

        container.setBackground(new java.awt.Color(255, 255, 255));

        bandImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IHM/logo.ico.jpg"))); // NOI18N

        welcomeText.setFont(new java.awt.Font("Bodoni MT Black", 2, 36)); // NOI18N
        welcomeText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeText.setText("Carnet de contacts");

        newContactButton.setText("Nouveau contact");
        newContactButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newContactButtonActionPerformed(evt);
            }
        });

        listContactButton.setText("Liste de contacts");
        listContactButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listContactButtonActionPerformed(evt);
            }
        });

        storageButton.setText("Enregistrer");
        storageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storageButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerLayout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(welcomeText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(containerLayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(newContactButton)
                        .addGap(95, 95, 95)
                        .addComponent(storageButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                        .addComponent(listContactButton)))
                .addGap(241, 241, 241))
            .addComponent(bandImage, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addComponent(bandImage, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(welcomeText, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(227, 227, 227)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newContactButton)
                    .addComponent(listContactButton)
                    .addComponent(storageButton))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newContactButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newContactButtonActionPerformed
        boolean test = true;
        if(createFrame == null){
            createFrame = new CreateContact();
        }else{
            while(test){
                if(createFrame!= null && createFrame.getNouveau()!= null){
                    liste.ajouterContact(createFrame.getNouveau());
                    test = false;
                }
            }
            createFrame.setVisible(true);
        }
    }//GEN-LAST:event_newContactButtonActionPerformed

    private void listContactButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listContactButtonActionPerformed
        boolean test = true;
        if(listeContact == null){
            listeContact = new AfficheContact();
        }else{
            while(test){
                if(listeContact!= null && createFrame.getNouveau()!= null){
                    listeContact.insertContact(liste);
                    test = false;
                }
            }
            listeContact.setVisible(true);
        }
    }//GEN-LAST:event_listContactButtonActionPerformed

    private void storageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storageButtonActionPerformed
        
        this.enregistrer(connect);
    }//GEN-LAST:event_storageButtonActionPerformed

    private void onWindowsClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_onWindowsClosed
        if(connect!=null){
            try{
                connect.close();
                System.out.println("Connexion fermée.");
            }catch(SQLException sqlex){
                System.out.println("Nous n'avons pas pu fermer la connexion.");
            }
        }
    }//GEN-LAST:event_onWindowsClosed

    private void enregistrer(Connection connect){
        for(Contact contact:liste.getRepertoire()){
            contact.insertIntoBD(connect);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrmApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrmApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrmApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrmApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrmApplication().setVisible(true);
            }
        });
        try{
            Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
        }catch (Exception ex){
            System.out.println("Erreur de chargement du driver");
        }
        String user = "root";//Dans mon cas
        String password = "Qosascomp20?";
        String port = "3306";
        //S'assurer de mettre en route le serveur MySQL avant d'exécuter
        try{
            connect = DriverManager.getConnection("jdbc:mysql://localhost:"+port+"/Contact?"+"user="+user+"&password="+password);
            
        }catch(SQLException sqlex){
            System.out.println("Un problème avec la requête est survenu!!!");
            System.out.println(sqlex.getMessage());
            sqlex.printStackTrace();
        }catch(Exception e){
            System.out.println("Un problème est survenu!!");
            e.printStackTrace();
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bandImage;
    private javax.swing.JPanel container;
    private javax.swing.JButton listContactButton;
    private javax.swing.JButton newContactButton;
    private javax.swing.JButton storageButton;
    private javax.swing.JLabel welcomeText;
    // End of variables declaration//GEN-END:variables
}
